import randomArray from "../helpers/randomArray";
import UserModel from "../models/UserModel";

export const users: UserModel[] = Array.from({ length: 100 }, (_, index) => {
  const username = randomArray(names);
  const email = username + "@gmail.com";
  const password = username + "123";
  return {
    id: index,
    username: username,
    email: email,
    password: password,
    photoProfile: "https://picsum.photos/seed/human/1080/1080",
    provider: "email",
    role: "user",
    isVerified: true,
    verificationCode: null,
    verificationRequestDate: null,
  };
});

const names = [
  "trelawneybarera",
  "morganabarera",
  "lockhartbarera",
  "bareradobby",
  "friarbarera",
  "bareraaccio",
  "animagusbarera",
  "cleansweepbarera",
  "bareramarge",
  "pettigrewbarera",
  "barerahermione",
  "secretsbarera",
  "bareraniffler",
  "fawkesbarera",
  "vellabarera",
  "bluebottlebarera",
  "bareradoxy",
  "pigwidgeonbarera",
  "bareranorbert",
  "mimsybarera",
  "bareragillyweed",
  "bareramarvolo",
  "bareraowls",
  "ritabarera",
  "finniganbarera",
  "barerawinky",
  "sherbertbarera",
  "barerakedavra",
  "barerasupplies",
  "barerawormtail",
  "barerahogwarts",
  "bareraviktor",
  "travelsbarera",
  "bareramyrtle",
  "malfoybarera",
  "bareracornelius",
  "beaterbarera",
  "erklingbarera",
  "gnomebarera",
  "aurorbarera",
  "crabbebarera",
  "horntailbarera",
  "bareraowlery",
  "jarveybarera",
  "bareranarcissa",
  "barerahogsmead",
  "filchbarera",
  "bareraquirrell",
  "barerabludger",
  "triwizardbarera",
  "bareraalbus",
  "barerakappas",
  "imperiousbarera",
  "longbottombarera",
  "bareradurmstrang",
  "diagonbarera",
  "bareraprongs",
  "bareramudblood",
  "flitwickbarera",
  "severusbarera",
  "barerawarbeck",
  "colinbarera",
  "bareramillicent",
  "barerafortuna",
  "bareraollivander",
  "bareradursley",
  "catchpolebarera",
  "bareradraconis",
  "keeperbarera",
  "bareragoyle",
  "robesbarera",
  "bareramalkin",
  "barerachang",
  "barerabathilda",
  "imperiobarera",
  "bareraspinnet",
];
