import AwardModel from "../models/AwardModel";

export const awards: AwardModel[] = [
  {
    id: 1,
    name: "Best Picture",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 2,
    name: "Best Director",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 3,
    name: "Best Actor",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 4,
    name: "Best Actress",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 5,
    name: "Best Supporting Actor",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 6,
    name: "Best Supporting Actress",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 7,
    name: "Best Original Screenplay",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 8,
    name: "Best Adapted Screenplay",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 9,
    name: "Best Animated Feature",
    year: new Date(2020),
    countryCode: "KR",
  },
  {
    id: 10,
    name: "Best International Feature",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 11,
    name: "Best Documentary Feature",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 12,
    name: "Best Original Score",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 13,
    name: "Best Original Song",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 14,
    name: "Best Sound Editing",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 15,
    name: "Best Sound Mixing",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 16,
    name: "Best Production Design",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 17,
    name: "Best Cinematography",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 18,
    name: "Best Makeup and Hairstyling",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 19,
    name: "Best Costume Design",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 20,
    name: "Best Film Editing",
    year: new Date(2020),
    countryCode: "JP",
  },
  {
    id: 21,
    name: "Best Visual Effects",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 22,
    name: "Best Animated Short",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 23,
    name: "Best Documentary Short",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 24,
    name: "Best Live Action Short",
    year: new Date(2020),
    countryCode: "US",
  },
  {
    id: 25,
    name: "Best Director",
    year: new Date(2020),
    countryCode: "ID",
  },
];